### PR TITLE
Validate NotContains 

### LINKED ISSUE #45: Implement NotContains
## Description:
- Implement a NotContains check
- healthz returns pass, warn or fail
- pass or warn are valid
- there's currently no way to check for that

### LINKED ISSUE #46: Implement json property not present
## Description
- deathYear (and other fields) should not be present if null
- there is currently not a way to validate a json property is not present

### PR DESCRIPTION
**Pull request by mag16**
## Type of PR

- [ ] Documentation changes
- [X] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
- implement NotContains check.

## Issues Closed or Referenced

- Closes #45 
- Closes #46

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -8,6 +8,7 @@
 *.user
 *.userosscache
 *.sln.docstates
+*.json
```
Comment (bartr) [inline .gitignore]: this can't be excluded as the test files are json

File: src/app/Validators/ParametersValidator.cs [hunk 2]
```diff
@@ -373,5 +373,32 @@ public static ValidationResult ValidatePath(string path)
 
             return res;
         }
+
+        /// <summary>
+        /// validate NotContains
+        /// </summary>
+        /// <param name="contains">list of string</param>
+        /// <returns>ValidationResult</returns>
+        public static ValidationResult ValidateNotContains(List<string> contains)
```
Comment (bartr) [inline src/app/Validators/ParametersValidator.cs]: naming confusion

File: src/app/Validators/ParametersValidator.cs [hunk 3]
```diff
@@ -373,5 +373,32 @@ public static ValidationResult ValidatePath(string path)
...
+            // null check
+            if (contains == null || contains.Count == 0)
+            {
+                return res;
+            }
+
+            // validate each value
+            foreach (string c in contains)
+            {
+                if (!string.IsNullOrEmpty(c))
```
Comment (bartr) [inline src/app/Validators/ParametersValidator.cs]: bug - shouldn't have a not - this cannot have passed unit tests, so there's a missing unit test as well

File: src/app/Validators/ResponseValidator.cs [hunk 4]
```diff
@@ -400,5 +401,31 @@ public static ValidationResult ValidateContains(List<string> containsList, strin
 
             return result;
         }
+
+        //validate NotContains
+        public static ValidationResult ValidateNotContains(List<string> containsList, string body)
```
Comment (bartr) [inline src/app/Validators/ResponseValidator.cs]: naming confusion

File: src/app/WebValidation/Model/Validation.cs [hunk 5]
```diff
@@ -11,6 +11,7 @@ public class Validation
         public int? MaxLength { get; set; }
         public int? MaxMilliseconds { get; set; }
         public List<string> Contains { get; set; } = new List<string>();
+        public List<string> NotContains { get; set; } = new List<string>();
```
Comment (bartr) [inline src/app/WebValidation/Model/Validation.cs]: do these need to be initialized to new List<>? It won't serialize properly if they are null.

File: src/app/TestFiles/dotnet.json [hunk 6]
```diff
@@ -1,7 +1,8 @@
 [
-  {"Path":"/index.html","PerfTarget":{"Category": "static"},"SortOrder":1,"Validation":{"ContentType":"text/html"}},
```
Comment (bartr) [inline src/app/TestFiles/dotnet.json]: why were these updated? Have they been thoroughly tested?

File: src/app/TestFiles/dotnet.json [hunk 7]
```diff
@@ -1,7 +1,8 @@
...
-  {"Path":"/swagger.json","PerfTarget":{"Category": "static"},"Validation":{"JsonObject":[{"Field":"openapi","Value":null},{"Field":"info","Value":null},{"Field":"paths","Value":null},{"Field":"components","Value":null}]}},
+  {"path":"/","perfTarget":{"category":"static"},"validation":{"statusCode":301}},
```
Comment (bartr) [inline src/app/TestFiles/dotnet.json]: Property should be PascalCase

File: src/app/Validators/ParametersValidator.cs [hunk 8]
```diff
@@ -373,5 +373,32 @@ public static ValidationResult ValidatePath(string path)
 
             return res;
         }
+
```
Comment (bartr) [inline src/app/Validators/ParametersValidator.cs]: Missing unit tests

File: .gitignore (hunk 1 above)
Comment (mag16) [reply .gitignore]: removed.

File: src/app/Validators/ParametersValidator.cs (hunk 2 above)
Comment (mag16) [reply src/app/Validators/ParametersValidator.cs]: renamed parameter to "notcontains".

File: src/app/Validators/ParametersValidator.cs (hunk 3 above)
Comment (mag16) [reply src/app/Validators/ParametersValidator.cs]: ah i see..will remove.  Thanks Bart!!

File: src/app/Validators/ResponseValidator.cs (hunk 4 above)
Comment (mag16) [reply src/app/Validators/ResponseValidator.cs]: Bart, should that List be named "notcontainsList"? tia

File: src/app/Validators/ResponseValidator.cs [hunk 9]
```diff
@@ -403,19 +403,19 @@ public static ValidationResult ValidateContains(List<string> containsList, strin
         }
 
         //validate NotContains
-        public static ValidationResult ValidateNotContains(List<string> containsList, string body)
+        public static ValidationResult ValidateNotContains(List<string> notcontainsList, string body)
```
Comment (bartr) [inline src/app/Validators/ResponseValidator.cs:406]: should be notContainsList - does fxcop not catch this?

File: src/app/Validators/ResponseValidator.cs [hunk 10]
```diff
@@ -403,19 +403,19 @@ public static ValidationResult ValidateContains(List<string> containsList, strin
...
             ValidationResult result = new ValidationResult();
 
-            if (containsList == null || containsList.Count == 0)
+            if (notcontainsList == null || notcontainsList.Count == 0)
             {
                 return result;
             }
 
-            if (!string.IsNullOrEmpty(body) && containsList != null && containsList.Count > 0)
+            if (!string.IsNullOrEmpty(body) && notcontainsList != null && notcontainsList.Count > 0)
```
Comment (bartr) [inline src/app/Validators/ResponseValidator.cs:415]: last two checks shouldn't be necessary as they were just checked

**Comment by bartr** [comment]
I don't think this addresses #46 does it?

File: src/app/TestFiles/dotnet.json (hunk 6 above)
Comment (mag16) [reply src/app/TestFiles/dotnet.json:2]: I may have pulled these in by mistake from generate-webv-json (had removed the SortOrder  property).

File: src/app/WebValidation/Model/Validation.cs (hunk 5 above)
Comment (mag16) [reply src/app/WebValidation/Model/Validation.cs:14]: Bart should i set as **public List<string> NotContains { get; set; }**

File: src/app/TestFiles/baseline.json [hunk 11]
```diff
@@ -1,12 +1,11 @@
...
...ue":1953},{"index":3,"field":"category","value":"Actor"},{"index":3,"field":"name","value":"Tchéky Karyo"},{"index":3,"field":"order","value":4},{"index":3,"field":"characters","validation":{"jsonArray":{"count":1,"byIndex":[{"index":0,"value":"Anton"}]}}},{"index":4,"field":"actorId","value":"nm0001162"},{"index":4,"field":"birthYear","value":1955},{"index":4,"field":"category","value":"Director"},{"index":4,"field":"name","value":"Griffin Dunne"},{"index":4,"field":"order","value":5},{"index":5,"field":"actorId","value":"nm0628352"},{"index":5,"field":"birthYear","value":1956},{"index":5,"field":"category","value":"Producer"},{"index":5,"field":"name","value":"Robert F. Newmyer"},{"index":5,"field":"order","value":7},{"index":5,"field":"deathYear","value":2005},{"index":6,"field":"actorId","value":"nm0798711"},{"index":6,"field":"birthYear","value":1997},{"index":6,"field":"category","value":"Producer"},{"index":6,"field":"name","value":"Jeffrey Silver"},{"index":6,"field":"order","value":8}]}}},{"index":39,"field":"id","value":"tt1067765"},{"index":39,"field":"movieId","value":"tt1067765"},{"index":39,"field":"title","value":"Adult World"},{"index":39,"field":"type","value":"Mov
```
Comment (aflinchb) [inline src/app/TestFiles/baseline.json:9]: I still see this ietf endpoint is checking for {"field":"status","value":"pass"} in a few places, should that be removed?

Comment (aflinchb) [reply src/app/TestFiles/baseline.json:9]: (same question in benchmark.json)

**Comment by aflinchb** [comment]
> I don't think this addresses #46 does it?

I have the same question - but does that issue cover adding the death year tests to the test files or just the not contains functionality?

**Comment by bartr** [comment]
It covers both by using a notContains “deathYear”: on the json payload. We need to add that test to the generator- I’ll do that today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

File: src/app/TestFiles/baseline.json (hunk 11 above)
Comment (bartr) [reply src/app/TestFiles/baseline.json]: I don't think it should be as those are the test cases and we want to notify if one of those doesn't pass so that we know which request it was. We can change to a notContains("fail") but I like having the check for "pass"
